import { notFound } from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import { compileMDX } from 'next-mdx-remote/rsc';
import remarkGfm from 'remark-gfm';
import { getItem, getItems } from '@/lib/content';
import { siteConfig } from '@/config/site';
export function generateStaticParams() { return getItems('project').map((project) => ({ slug: project.slug })); }
export async function generateMetadata({ params }: { params: { slug: string } }) { const project = getItem('project', params.slug); return project ? { title: `${String(project.title)} — ${siteConfig.person.name}`, description: project.description } : {}; }
export default async function ProjectPage({ params }: { params: { slug: string } }) { const project = getItem('project', params.slug); if (!project) notFound(); const { content } = await compileMDX({ source: project.content, options: { mdxOptions: { remarkPlugins: [remarkGfm] } } }); return <main><div className="wrap"><article className="detail project-detail"><Link className="detail-back mono" href="/projects">← 返回作品</Link><header className="detail-header"><div className="detail-kicker mono">{String(project.type).toUpperCase()} / {project.date}</div><h1>{String(project.title)}</h1><p className="detail-description">{String(project.description)}</p><div className="detail-meta mono">{String(project.status)} · {project.tags.join(' · ')}</div><div className={`project-banner ${String(project.color)}${project.image ? ' has-image' : ''}`}>{project.image && <Image className="project-banner-img" src={String(project.image)} alt={String(project.title)} fill sizes="1100px" />}<span className="project-side">PROJECT / {String(project.date).slice(0, 4)}</span></div><div className="detail-links">{project.link && <a className="button primary" href={String(project.link)} target="_blank" rel="noreferrer">访问项目 ↗</a>}{project.github && <a className="button" href={String(project.github)} target="_blank" rel="noreferrer">查看源码 ↗</a>}</div></header><div className="prose">{content}</div></article></div></main>; }
