export const siteConfig = {
  url: 'https://person.deerblock.cn',
  person: {
    name: 'Paul',
    role: '独立开发者 / 前端游戏研发工程师',
    location: '上海 / 中国',
    email: 'hello@leonxlnx.com',
    intro: '我是 Paul，一个在上海工作的独立开发者。6 年前端研发经验，曾任喜马拉雅游戏研发工程师，主导过千万级 DAU 产品的核心开发与技术沉淀。喜欢做有创意、有思考、也有挑战的东西。',
    aboutLead: '我喜欢做一些有创意、但不只是为了好看的事情。我希望每个作品背后都有思考，也愿意接受足够的挑战。',
    aboutDetail: '最重要的是先解决真实的问题，其次才是追求自己喜欢的表达。',
    aboutPageIntro: '一个有趣的独立开发者，正在学习如何把复杂的东西做得简单一点。',
    aboutPageDetail: '我在意别人的评价，也在意产品真正的价值表达；但如果别人不喜欢，也只能接受，哈哈。',
    facts: [
      ['BASE', '上海 / 中国'],
      ['STATUS', '自由接案中'],
      ['EXPERIENCE', '6 年前端研发 · 3 年游戏/互动方向'],
      ['STACK', 'TypeScript · React · Cocos Creator · Next.js'],
      ['COFFEE', '手冲 / 不加糖'],
    ],
  },
  brand: {
    label: '鲍磊 / 独立开发者',
    footer: '© 2025 鲍磊 — MADE WITH CURIOSITY',
  },
  navigation: [
    { label: '作品', href: '/projects' },
    { label: '杂记', href: '/posts' },
    { label: '关于', href: '/about' },
  ],
  home: {
    eyebrow: '独立开发 · 设计 · 写作',
    headline: '把想法做成',
    headlineAccent: '值得使用的东西。',
    primaryCta: '看我的作品 ↘',
    secondaryCta: '认识我',
    orbitLabel: 'MAKE / NOTICE / REPEAT',
    orbitTags: ['CURRENTLY|EXPLORING_', 'OPEN TO|GOOD IDEAS ✦'],
    ticker: ['SELECTED WORKS ✳ 2021—2025', 'CODE WITH INTENTION →', 'LESS, BUT BETTER'],
    featuredProjectLimit: 4,
    recentPostLimit: 4,
    workSectionTitle: '精选作品',
    notesSectionTitle: '最近杂记',
    notesIntro: '记录一些还没有答案的问题，和路上遇见的风景。',
    aboutTitle: '你好，我是 {name}。',
    aboutAccent: '喜欢从零开始。',
    contactTitle: '有一个想法？',
    contactAccent: '我们把它做成真的。',
  },
  aboutInterview: {
    eyebrow: 'ABOUT / A CONVERSATION',
    title: '关于我，\n我是一个有趣的人。',
    intro: '我想把这里做成一场持续发生的对话：关于我如何工作、相信什么，以及正在把什么交给世界。过去几年，我作为独立开发者在接项目、服务客户的间隙中，不断提炼真实需求、孵化自己的产品。这大概是我的心路历程。',
    questions: [
      {
        question: '你为什么做东西？',
        answer: '从给客户做定制开发，到打磨 FateMesh 这种 AI 命理智能体平台，我始终被「把抽象逻辑变成可感知的交互体验」这件事吸引。做东西不是为了技术炫技，而是想看看：代码真的能改变一个人学习、决策、生活的方式吗？每个真实项目里的痛点，都是下一个产品的种子。',
        principle: '代码服务于体验，体验服务于真实价值。',
        evidence: 'projects',
      },
      {
        question: '你怎么看待好的产品？',
        answer: '接触过各行各业的客户项目后，我更笃定：再酷的技术、再美的动效，如果不解决客户真实的商业问题、用户痛点，就是自嗨。现在我先问：谁在为此买单？什么场景下会用？能不能复用？然后才考虑技术栈和表达。这种「先业务后技术」的直觉，是无数个甲方项目练出来的。',
        principle: '先搞清商业/用户价值，再谈技术实现与表达。',
        evidence: 'projects',
      },
      {
        question: '你如何与不确定性相处？',
        answer: '客户需求常常模糊、多变，我学会了：先把核心链路跑通（MVP），把易变的业务配置化、组件化，把不变的工程基建沉淀下来。手头有 FateMesh、SpaceRoam 等自有产品在并行，客户项目的反哺让我不必赌单一押注。记录想法 → 快速验证 → 分享收集反馈 → 决定是否深耕，这是我应对不确定性的节奏。',
        principle: '固化核心，解耦变化，小步快跑，多线程试错。',
        evidence: 'posts',
      },
      {
        question: '独立开发这条路，最核心的收获是什么？',
        answer: '以前在大厂做增长线，资源现成、分工明确；现在独自面对：产品定义、技术选型、设计开发、部署上线、SEO 增长、商业化闭环、甚至法务财税。这逼着我建立了一套「极低成本把想法变成可用产品」的个人工作流：熟悉的技术栈（Next.js + TS + Tailwind）、可复用的组件库、标准化的发布流程、自动化的 CI/CD。这套工作流，才是我真正的护城河。',
        principle: '工具链和工作流的复利，比单个项目的成败更重要。',
        evidence: 'projects',
      },
    ],
    skills: [
      { name: '产品工程思维', detail: '从客户真实业务目标反推技术方案，而非为技术找场景。服务过教育、电商、文旅、金融等多行业项目，积累了跨领域的需求建模经验。' },
      { name: '游戏/互动前端', detail: 'Cocos Creator 深度开发：游戏模板引擎、动画系统、内存性能优化、Shader 编写、热更新机制。熟悉 WebGL 渲染管线。' },
      { name: '全栈 Web 构建', detail: 'React/Next.js/TypeScript 生产级应用：从架构设计、组件库沉淀、CI/CD 到上线运维。熟悉 Node.js、RESTful/GraphQL、WebSocket 实时通信。' },
      { name: '跨端与工程化', detail: 'React Native / H5+ / 微信小程序多端复用经验。擅长 Webpack/Vite 构建优化、Monorepo 管理、基础库沉淀、自动化发布流程。' },
      { name: '0→1 独立产品', detail: 'FateMesh（AI 命理平台）、SpaceRoam（3D 漫游工具）等从概念到上线的完整经历：产品定义、技术选型、设计开发、SEO/增长、商业化闭环。' },
    ],
    services: [
      { name: '网站 / Landing Page', detail: '从信息架构、视觉方向到前端实现，做一个真正能代表你的网页。', tags: ['设计方向', '响应式', 'Next.js', 'SEO 就绪'] },
      { name: '产品前端开发', detail: '把已有设计或模糊想法，变成可用、可上线、可继续迭代的产品前端。', tags: ['React', 'TypeScript', '动效', '工程化'] },
      { name: '游戏/互动应用开发', detail: 'Cocos Creator / WebGL 方向：小游戏、互动课件、3D 漫游、可视化大屏。', tags: ['Cocos', 'TypeScript', 'Shader', '性能优化'] },
      { name: '技术架构与工程化咨询', detail: '前端架构选型、组件库设计、构建优化、团队研发规范建设、Code Review 机制。', tags: ['架构', 'Monorepo', 'CI/CD', '团队效能'] },
    ],
    process: ['聊清问题与业务目标', '确定技术方向与 MVP 范围', '快速实现核心闭环', '上线收集反馈持续迭代'],
    showcase: [
      { label: '作品', href: '/projects', description: 'FateMesh、SpaceRoam 等从 0 到 1 的独立产品。' },
      { label: '文章', href: '/posts', description: '关于技术、设计、独立开发和生活的思考。' },
      { label: '联系我', href: '/#contact', description: '如果你有一个值得认真做的想法。' },
    ],
  },
  social: [
    { label: 'GITHUB ↗', href: 'https://github.com/noconfuse' },
    { label: '公众号 · 所遇非良人', href: '' },
    { label: 'EMAIL ↗', href: 'mailto:hello@leonxlnx.com' },
  ],
} as const;

export type SiteConfig = typeof siteConfig;
